# Generated by Django 5.2.10 on 2026-01-15 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7c19366c-d4df-4145-9495-c02006b9b0d3'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0–100)', max_digits=5)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('picture', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_shop_app.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_shop_app.shop')),
            ],
        ),
    ]
