# Generated by Django 5.2.10 on 2026-01-15 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_shop_app', '0002_remove_product_picture_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5852ce47-1d9d-41b3-a343-1363b7c7948d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
