# Generated by Django 5.2.10 on 2026-01-15 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_shop_app', '0004_alter_product_category_alter_product_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adacc9c3-83e8-4fda-8b5c-ff1b377bb38d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
