# Generated by Django 5.2.10 on 2026-01-15 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_shop_app', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b633f46-f068-48ec-821e-c9cb74d37d29'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
