# Generated by Django 5.2.10 on 2026-01-15 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_shop_app', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97e8b11a-8772-4e88-8f4b-5cc5920c46f0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(max_length=100),
        ),
    ]
