# Generated by Django 5.2.10 on 2026-01-15 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_shop_app', '0007_alter_product_category_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9fe5edfb-7a1f-4af8-8231-6166137eac98'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
