# Generated by Django 5.2.10 on 2026-01-15 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_shop_app', '0009_alter_product_id_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1c1a8c2-4b4f-4f79-988c-164bff8601ee'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in rupiah'),
        ),
    ]
